# Generated by Django 5.0 on 2023-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_tokens_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
